import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const inter = localFont({
  src: [
    {
      path: '../fonts/Inter-Variable.ttf',
      style: 'normal',
    },
    {
      path: '../fonts/Inter-Italic-Variable.ttf',
      style: 'italic',
    },
  ],
  variable: '--font-inter',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-sans">{children}</body>
    </html>
  );
}
