/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/smol_ame_in_an_upcycled_terrarium_hololiveen.glb --transform -o src/components/SketchfabModel.tsx 
Files: public/models/smol_ame_in_an_upcycled_terrarium_hololiveen.glb [4.02MB] > /Users/alexandreduteau/Code/Personal/cisa/src/components/smol_ame_in_an_upcycled_terrarium_hololiveen-transformed.glb [434.26KB] (89%)
Author: Seafoam (https://sketchfab.com/seafoam)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/smol-ame-in-an-upcycled-terrarium-hololiveen-490cecc249d242188fda5ad3160a4b24
Title: Smol Ame in an Upcycled Terrarium [HololiveEn]
*/

'use client'

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Animation'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_10: THREE.SkinnedMesh
    Object_12: THREE.SkinnedMesh
    Object_14: THREE.SkinnedMesh
    Object_16: THREE.SkinnedMesh
    Object_18: THREE.SkinnedMesh
    Object_19: THREE.SkinnedMesh
    Object_21: THREE.SkinnedMesh
    Object_23: THREE.SkinnedMesh
    Object_25: THREE.SkinnedMesh
    Object_27: THREE.SkinnedMesh
    Object_29: THREE.SkinnedMesh
    Object_31: THREE.SkinnedMesh
    Object_33: THREE.SkinnedMesh
    Object_35: THREE.SkinnedMesh
    Object_39: THREE.SkinnedMesh
    Object_41: THREE.SkinnedMesh
    Object_65: THREE.SkinnedMesh
    Object_67: THREE.SkinnedMesh
    Object_37: THREE.SkinnedMesh
    GLTF_created_0_rootJoint: THREE.Bone
    GLTF_created_1_rootJoint: THREE.Bone
  }
  materials: {
    pasokon: THREE.MeshStandardMaterial
    terrarium1: THREE.MeshStandardMaterial
    terrarium1ame: THREE.MeshStandardMaterial
    terrarium1ameoutline: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function SketchfabModel(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/models/smol_ame_in_an_upcycled_terrarium_hololiveen-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
    const action = actions['Animation']
    if (!action) return
    action.reset().play()
    return () => {
      action.stop()
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <primitive object={nodes.GLTF_created_1_rootJoint} />
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.pasokon} />
        <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.terrarium1} />
        <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.terrarium1ame} skeleton={nodes.Object_10.skeleton} position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]} />
        <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.terrarium1ameoutline} skeleton={nodes.Object_12.skeleton} position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]} />
        <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.terrarium1ame} skeleton={nodes.Object_14.skeleton} position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]} />
        <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.terrarium1ameoutline} skeleton={nodes.Object_16.skeleton} position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]} />
        <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.terrarium1ame} skeleton={nodes.Object_18.skeleton} position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]} />
        <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.terrarium1ameoutline} skeleton={nodes.Object_19.skeleton} position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]} />
        <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.terrarium1ameoutline} skeleton={nodes.Object_21.skeleton} position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]} />
        <skinnedMesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.terrarium1ame} skeleton={nodes.Object_23.skeleton} position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]} />
        <skinnedMesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.terrarium1ame} skeleton={nodes.Object_25.skeleton} position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]} />
        <skinnedMesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.terrarium1ameoutline} skeleton={nodes.Object_27.skeleton} position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]} />
        <skinnedMesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.terrarium1ame} skeleton={nodes.Object_29.skeleton} position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]} />
        <skinnedMesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.terrarium1ameoutline} skeleton={nodes.Object_31.skeleton} position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]} />
        <skinnedMesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.terrarium1ame} skeleton={nodes.Object_33.skeleton} position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]} />
        <skinnedMesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.terrarium1ameoutline} skeleton={nodes.Object_35.skeleton} position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]} />
        <skinnedMesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.terrarium1ame} skeleton={nodes.Object_39.skeleton} position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]} />
        <skinnedMesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.terrarium1ameoutline} skeleton={nodes.Object_41.skeleton} position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]} />
        <skinnedMesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.terrarium1} skeleton={nodes.Object_65.skeleton} position={[0, 0.864, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.073} />
        <skinnedMesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.terrarium1ameoutline} skeleton={nodes.Object_67.skeleton} position={[0, 0.864, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.073} />
        <skinnedMesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.terrarium1ame} skeleton={nodes.Object_37.skeleton} morphTargetDictionary={nodes.Object_37.morphTargetDictionary} morphTargetInfluences={nodes.Object_37.morphTargetInfluences} position={[-0.197, 0.901, 0]} rotation={[0, 0.864, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/smol_ame_in_an_upcycled_terrarium_hololiveen-transformed.glb')
